server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      reply-timeout: 5000

  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_message
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:  # ← Должен быть на уровне datasource, НЕ внутри!
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 2y8duqie8fjrk4i8ssifj339difjei8s
  lifetime: 30m