server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_users
    username: messenger_admin
    password: admin_pass
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      reply-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
